CXXFLAGS:=-m32 -fPIC
LDFLAGS:=-m32 -shared -Wl,--version-script=dmsqlite.x


release: CXXFLAGS+= -O3
release: LDFLAGS+= -O3
release: all
	strip dmsqlite.so

debug: CXXFLAGS+= -g -Wall -ansi -pedantic
debug: all


all: dmsqlite.so

clean:
	rm -f dmsqlite.o dmsqlite.so

dmsqlite.so: dmsqlite.o
	g++ ${LDFLAGS} -o dmsqlite.so dmsqlite.o -lsqlite3

dmsqlite.o: dmsqlite.cpp
	g++ ${CXXFLAGS} -c dmsqlite.cpp

