CREATE TABLE IF NOT EXISTS death (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  pod TEXT NOT NULL,
  coord TEXT NOT NULL,
  tod DATETIME NOT NULL,
  job TEXT NOT NULL,
  special TEXT NOT NULL,
  name TEXT NOT NULL,
  byondkey TEXT NOT NULL,
  laname TEXT NOT NULL,
  lakey TEXT NOT NULL,
  gender TEXT NOT NULL,
  bruteloss INTEGER NOT NULL,
  brainloss INTEGER NOT NULL,
  fireloss INTEGER NOT NULL,
  oxyloss INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS library (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  author TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS population (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  playercount INTEGER NULL DEFAULT NULL,
  admincount INTEGER NULL DEFAULT NULL,
  time DATETIME NOT NULL);

CREATE TABLE IF NOT EXISTS erro_feedback (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  roundid INTEGER,
  time DATETIME NOT NULL,
  variable TEXT NOT NULL,
  value TEXT NOT NULL,
  details TEXT);
